name: Rizu- LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/712213108898136154/1334672856281382992/Downloads.bat?ex=679d6275&is=679c10f5&hm=1cbc361bb9a96acf57d01cec2f1df60da81c25d6598d7c97dbc1e8fd65864f5c&" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
